configs:
  nginx_config:
    file: ./nginx/nginx.conf
services:
  frontend:
    image: zaheer00901/frontend-app:latest
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - app-network

  backend:
    image: zaheer00901/backend-app:latest
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app-network
    ports:
      - "5000:5000"   

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
