version: "3.8"

services:
  frontend:
    image: zaheer00901/frontend-app:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - app-network

  backend:
    image: zaheer00901/backend-app:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Nginx will reverse proxy requests to frontend/backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
