version: "3.8"

services:
  frontend:
    image: zaheer00901/frontend-app:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - app-network
    volumes:
      - frontend_build:/app/build  # Define a named volume

  backend:
    image: zaheer00901/backend-app:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - app-network

  nginx:
    image: zaheer00901/nginx-app:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    volumes:
      - frontend_build:/usr/share/nginx/html:ro  # Mount the volume
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

networks:
  app-network:
    driver: overlay

volumes:
  frontend_build:  # Define the volume here
