---
- name: Configure Firewall Rules
  hosts: webserver
  become: yes

  tasks:
    - name: Allow SSH
      ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: Allow HTTP (80)
      ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: Allow HTTPS (443)
      ufw:
        rule: allow
        port: "443"
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled
        policy: allow
